/**
 * POST /api/export
 *
 * Body: {
 *   thread: ScanThread,            // sent from the client since v0 stores threads in localStorage
 *   target: "issue" | "commit",
 *   repo:   "owner/repo"
 * }
 *
 * Response: { url: string }
 *
 * Requires a valid signed GitHub OAuth cookie.
 */
import { NextResponse } from "next/server";
import { getCfEnv } from "@/lib/cf-env";
import type { ScanThread } from "@/core";
import { readAuthCookie } from "@/lib/auth-cookie";

export const runtime = "edge";

interface Env {
  GITHUB_CLIENT_SECRET?: string;
  AUTH_SECRET?: string;
}
function getEnv(): Env { return getCfEnv<Env>(); }

interface ExportBody {
  thread: ScanThread;
  target: "issue" | "commit";
  repo: string;
}

function renderReport(thread: ScanThread): string {
  const r = thread.result;
  const stamp = new Date(thread.createdAt).toISOString();
  const mutations = r.mutations?.length ? r.mutations : [r.mutation].filter(Boolean);
  return [
    `# DELUSION REPORT :: ${r.tier.toUpperCase()} :: ${r.score}/100`,
    "",
    `_Generated by [scopecreeper.ai](https://scopecreeper.ai) at ${stamp}._`,
    "",
    `**Reality Score**: ${r.realityScore ?? "n/a"}/100`,
    `**Illusion Score**: ${r.illusionScore ?? "n/a"}/100`,
    `**Delusion Score**: ${r.score}/100  →  **${r.verdict}**`,
    "",
    "## Verdict",
    r.analysis,
    "",
    "## Mutations",
    ...mutations.map((m, i) => `${i + 1}. ${m}`),
    "",
    "## Source payload",
    "```",
    thread.input.payload.slice(0, 4000),
    "```",
  ].join("\n");
}

export async function POST(request: Request): Promise<Response> {
  const env = getEnv();
  const secret = env.AUTH_SECRET ?? `${env.GITHUB_CLIENT_SECRET ?? ""}::sc-auth`;
  const token = await readAuthCookie(request, secret);
  if (!token) {
    return NextResponse.json({ error: "not authenticated" }, { status: 401 });
  }

  let body: ExportBody;
  try {
    body = (await request.json()) as ExportBody;
  } catch {
    return NextResponse.json({ error: "invalid JSON" }, { status: 400 });
  }
  if (!body?.thread || !body?.target || !body?.repo) {
    return NextResponse.json(
      { error: "missing thread, target, or repo" },
      { status: 400 }
    );
  }

  const [owner, repo] = body.repo.split("/");
  if (!owner || !repo) {
    return NextResponse.json(
      { error: "repo must be owner/repo" },
      { status: 400 }
    );
  }

  const report = renderReport(body.thread);
  const ghHeaders = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "User-Agent": "scopecreeper",
    "Content-Type": "application/json",
  };

  if (body.target === "issue") {
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues`,
      {
        method: "POST",
        headers: ghHeaders,
        body: JSON.stringify({
          title: `DELUSION REPORT :: ${body.thread.result.tier.toUpperCase()} :: ${body.thread.result.score}/100`,
          body: report,
          labels: ["scope-creeper"],
        }),
      }
    );
    if (!res.ok) {
      const detail = await res.text();
      return NextResponse.json(
        { error: `GitHub responded ${res.status}`, detail },
        { status: 502 }
      );
    }
    const data = (await res.json()) as { html_url?: string };
    return NextResponse.json({ url: data.html_url ?? "" });
  }

  // commit DELUSION_REPORT.md to default branch
  const repoRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}`,
    { headers: ghHeaders }
  );
  if (!repoRes.ok) {
    return NextResponse.json(
      { error: `repo lookup failed: ${repoRes.status}` },
      { status: 502 }
    );
  }
  const repoData = (await repoRes.json()) as { default_branch?: string };
  const branch = repoData.default_branch ?? "main";

  // Check if file exists for SHA (needed on update).
  const path = "DELUSION_REPORT.md";
  let sha: string | undefined;
  const existing = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${branch}`,
    { headers: ghHeaders }
  );
  if (existing.ok) {
    const e = (await existing.json()) as { sha?: string };
    sha = e.sha;
  }

  // base64 encode the report.
  const utf8 = new TextEncoder().encode(report);
  let bin = "";
  for (const b of utf8) bin += String.fromCharCode(b);
  const content = btoa(bin);

  const commit = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      method: "PUT",
      headers: ghHeaders,
      body: JSON.stringify({
        message: `chore: delusion report (score ${body.thread.result.score})`,
        content,
        branch,
        sha,
      }),
    }
  );
  if (!commit.ok) {
    const detail = await commit.text();
    return NextResponse.json(
      { error: `commit failed: ${commit.status}`, detail },
      { status: 502 }
    );
  }
  const data = (await commit.json()) as {
    content?: { html_url?: string };
    commit?: { html_url?: string };
  };
  return NextResponse.json({
    url: data.content?.html_url ?? data.commit?.html_url ?? "",
  });
}
