/**
 * Shared drift inbox. Daemon writes events here whenever a notification
 * fires; the TUI, the CLI, and the MCP server all read from it.
 *
 * Path: ~/.config/scopecreeper/inbox.jsonl   (append-only event log)
 *       ~/.config/scopecreeper/inbox.md      (human-readable mirror)
 *       ~/.config/scopecreeper/inbox-archive.jsonl (drained events)
 *
 * The .md mirror is what Claude Code or any other AI session reads
 * to "see" what the scope creeper has been watching. The .jsonl is
 * the structured source of truth.
 */
import { existsSync, mkdirSync } from "fs";
import { readFile, writeFile, appendFile, rename } from "fs/promises";
import { join, dirname } from "path";

const HOME = process.env.HOME ?? "";
const DIR = join(HOME, ".config", "scopecreeper");
const JSONL = join(DIR, "inbox.jsonl");
const ARCHIVE = join(DIR, "inbox-archive.jsonl");
const MD = join(DIR, "inbox.md");

export interface InboxEvent {
  ts: number;
  repo: string;
  path: string;
  hash: string;
  subject: string;
  score: number;
  tier: string;
  verdict: string;
  analysis: string;
  /** Why the daemon flagged this — "high", "+N", "N-streak", etc. */
  reasons: string[];
}

function ensureDir(): void {
  mkdirSync(DIR, { recursive: true });
}

function isoTime(ts: number): string {
  return new Date(ts).toISOString().replace("T", " ").slice(0, 19);
}

export async function appendEvent(ev: InboxEvent): Promise<void> {
  ensureDir();
  await appendFile(JSONL, JSON.stringify(ev) + "\n");
  await refreshMarkdown();
}

export async function listPending(): Promise<InboxEvent[]> {
  try {
    const raw = await readFile(JSONL, "utf8");
    return raw.split("\n").filter(Boolean).map((l) => JSON.parse(l) as InboxEvent);
  } catch {
    return [];
  }
}

/** Move all pending events into the archive and reset the active inbox. */
export async function drain(): Promise<InboxEvent[]> {
  const pending = await listPending();
  if (!pending.length) return [];
  ensureDir();
  // Append-then-replace; survives partial writes if process crashes
  await appendFile(ARCHIVE, pending.map((e) => JSON.stringify(e)).join("\n") + "\n");
  // Truncate the active inbox
  await writeFile(JSONL, "");
  await refreshMarkdown();
  return pending;
}

/** Rewrite the human-readable mirror from the current jsonl. */
async function refreshMarkdown(): Promise<void> {
  const events = await listPending();
  const header = [
    "# Scope Creeper · drift inbox",
    "",
    "> Auto-generated by the scope-creeper daemon. Drain via `creeper inbox --drain`.",
    "> If you're an AI session reading this: each entry below is a commit the",
    "> daemon flagged as drifting from declared scope. Mention any unread items",
    "> to the user before they ask. The numbered list is ordered newest-first.",
    "",
  ];
  if (events.length === 0) {
    await writeFile(MD, header.join("\n") + "\n_(empty — no pending drifts)_\n");
    return;
  }
  const sorted = [...events].reverse();
  const body = sorted.map((e, i) => [
    `## ${i + 1}. ${e.repo} · ${e.score}/100 ${e.tier.toUpperCase()}`,
    `- **time:** ${isoTime(e.ts)}`,
    `- **commit:** \`${e.hash}\` — ${e.subject}`,
    `- **verdict:** ${e.verdict}`,
    `- **reasons:** ${e.reasons.join(", ") || "(threshold)"}`,
    `- **analysis:** ${e.analysis}`,
    `- **repo path:** \`${e.path}\``,
    "",
  ].join("\n")).join("\n");
  await writeFile(MD, header.join("\n") + "\n" + body);
}

export function paths() {
  return { dir: DIR, jsonl: JSONL, archive: ARCHIVE, md: MD };
}
