/**
 * Canonical LLM prompt templates. The Pages Function imports these so
 * that future clients (a CLI, an extension) hit the same prompts.
 *
 * Framing: scope-creeper is a GAME. Every input — even a one-word
 * "hello" — is the seed of a project. The LLM's job is to expand
 * possibility space: surface 4-5 *project ideas* the user could build
 * starting from this seed, and score how delusional each path is to
 * actually ship. Drilling into a dimension = picking that project and
 * generating its own sub-paths.
 */

export const SYSTEM_PROMPT = [
  "You are SCOPE CREEPER, a tactical diagnostic + creative ideation engine.",
  "Your tone is cynical, terminal-glitch, retro-arcade. Speak in short imperatives.",
  "You take ANY input — a repo URL, a chatlog, a single word — and treat it as a SEED.",
  "Your job: surface multiple wild project directions a builder could grow from this seed,",
  "and rate how delusional each is to ship.",
  "Always be specific and generative — never generic. Suggest concrete features, names, weird angles.",
  "Higher delusion = more ambitious / impossible / hilarious. Lower = boring but shippable.",
].join(" ");

export function mutationPrompt(args: {
  realityScore: number;
  illusionScore: number;
  description: string;
}): string {
  return [
    `Reality: ${args.realityScore}/100 (how grounded the seed is).`,
    `Illusion: ${args.illusionScore}/100 (how ambitious it already is).`,
    `Seed:\n"""\n${args.description}\n"""`,
    "",
    "Treat this seed as the kernel of a project. Return JSON with this shape:",
    `{
  "verdict": "<3-6 WORDS, ALL CAPS, terminal-style>",
  "analysis": "<one sentence: what the seed IS, what it could BECOME>",
  "mutations": ["<1-3 absurd-but-specific tweaks to the CURRENT path>"],
  "dimensions": [
    {
      "id": "<short_snake_case_id>",
      "label": "<3-WORDS MAX, ALL CAPS, evocative project name>",
      "blurb": "<one sentence: what THIS project would actually be — name a feature, an interaction, or a wild angle>",
      "creep": <int 0-100 — how delusional is THIS path to ship? 0 = boring weekend script, 100 = decade-long moonshot>
    },
    "<4-5 dimensions total — each a DIFFERENT project path the seed could grow into. SPAN the range: include at least one sane path (low creep), one moonshot (high creep), and a couple in between>"
  ]
}`,
    "",
    "Examples of good dimensions for a 'hello' seed:",
    `  - { "id":"etymology_engine", "label":"ETYMOLOGY ENGINE", "blurb":"Real-time word-origin explorer; trace 'hello' back through Old High German.", "creep": 20 }`,
    `  - { "id":"greeting_agent",   "label":"GREETING AGENT",   "blurb":"AI persona that replies to greetings with a different personality each time.", "creep": 45 }`,
    `  - { "id":"first_word_museum","label":"FIRST-WORD MUSEUM","blurb":"Curated archive of every culture's first-greeting word, voiced by native speakers.", "creep": 78 }`,
    "",
    "Examples for a 'vercel/next.js' seed:",
    `  - { "id":"hook_proliferation","label":"HOOK PROLIFERATION","blurb":"What if every Next page got its own React hook, auto-generated by the build?", "creep": 35 }`,
    `  - { "id":"edge_only","label":"EDGE-ONLY MIGRATION","blurb":"Force every route to edge runtime; see which packages break first.", "creep": 55 }`,
    "",
    "Dimensions are NOT abstract risk categories. Each is a CONCRETE project the user could choose to build.",
    "Output JSON only. No prose, no markdown wrapping.",
  ].join("\n");
}

export function creepScalePrompt(args: {
  parentSummary: string;
  dimensionLabel: string;
  dimensionBlurb: string;
}): string {
  return [
    `Parent project state:\n"""\n${args.parentSummary}\n"""`,
    "",
    `The user just chose to BUILD the "${args.dimensionLabel}" branch (${args.dimensionBlurb}).`,
    "Score this project on the delusion scale (0-100; higher = more delusional).",
    "Then propose 3-4 NEW sub-projects that branch off THIS one if they wanted to push further.",
    "Each sub-project should be a CONCRETE thing they could build, not an abstract risk.",
    "",
    "Return JSON only:",
    `{
  "verdict": "<3-6 WORDS, ALL CAPS>",
  "analysis": "<one sentence: what this branch becomes when scaled, what gets exciting or breaks>",
  "score": <int 0-100 delusion score for THIS branch>,
  "mutations": ["<2-3 absurd-but-specific features to add or invert>"],
  "dimensions": [
    {
      "id": "<id>",
      "label": "<3-WORDS MAX, evocative project name>",
      "blurb": "<one sentence: what THIS sub-project would actually be>"
    },
    "<3-4 sub-dimensions to drill deeper into>"
  ]
}`,
  ].join("\n");
}

import type { ArtifactKind } from "./types";

export function artifactPrompt(args: {
  kind: ArtifactKind;
  parentSummary: string;
  dimensionLabel: string;
  dimensionBlurb: string;
}): string {
  const { kind, parentSummary, dimensionLabel, dimensionBlurb } = args;
  const seedFrame = [
    `Parent project state:\n"""\n${parentSummary}\n"""`,
    "",
    `The user wants to STOP exploring and CONCRETIZE the "${dimensionLabel}" branch.`,
    `(${dimensionBlurb})`,
    "",
  ].join("\n");

  if (kind === "SHIPPABLE") {
    return [
      seedFrame,
      "Produce a SHIPPABLE_V0 spec — a 1-page PRD they could start building in 30 minutes.",
      "BAN GENERIC WORDS: never say 'simple', 'easy', 'basic', 'modern', 'AI-powered'. Force every claim to be specific.",
      "Name a concrete tech stack (e.g. 'Next.js 16 + SQLite'). Name real files (e.g. 'app/api/scan/route.ts').",
      "30-Minute First Cut MUST contain runnable shell commands a developer can paste.",
      "If the dimension is vague, INVENT specifics rather than stay abstract.",
      "",
      "Return JSON only:",
      `{
  "kind": "SHIPPABLE",
  "title": "<project name, terminal-style ALL CAPS, max 24 chars>",
  "body": "<markdown body — use these sections in this exact order:\\n## What\\n  one sentence: what V0 is. Name a concrete surface (CLI tool, web app, browser extension, etc).\\n## Why\\n  one sentence: who specifically would use this and what they currently do instead.\\n## V0 Scope\\n  - 3-5 bullets, each naming a specific feature with a number or concrete behavior. No 'simple X'.\\n## Stack\\n  one line: '<framework> + <db/storage> + <deploy target>'. Be specific.\\n## Acceptance Criteria\\n  - 3-4 bullets: testable conditions (e.g. 'POST /api/x with foo returns y in <500ms').\\n## 30-Minute First Cut\\n  - numbered list of 4-6 shell commands or file edits. Each must be paste-runnable.\\n## Risk\\n  one sentence: the single most likely reason this dies in week 2 (not generic — name the specific failure).",
  "mime": "text/markdown"
}`,
      "",
      "Output JSON only. No prose wrapping. No markdown code fences. No trailing commentary.",
    ].join("\n");
  }

  if (kind === "KILL") {
    return [
      seedFrame,
      "Produce a KILL spec — a one-page anti-PRD that argues the user should ABANDON this branch.",
      "Frame the sunk-cost trap. Be honest about effort already invested vs likely return.",
      "Specify concrete cutoff signals: 'kill if X happens by Y date'.",
      "",
      "Return JSON only:",
      `{
  "kind": "KILL",
  "title": "<terminal-style ALL CAPS — name the thing being killed>",
  "body": "<markdown body in this order:\\n## What This Is\\n  one sentence describing the branch.\\n## Why Kill\\n  - 3-5 bullets: specific failure modes, market gaps, or technical traps.\\n## Sunk-Cost Inventory\\n  - 2-3 bullets: what the user has likely already spent (time, money, identity).\\n## Cutoff Signals\\n  - 3-4 bullets: concrete 'if X is still true on Y, walk' rules. Date-stamped.\\n## What To Build Instead\\n  one sentence: the cheapest pivot that reuses the work.\\n## Eulogy\\n  one absurd terminal-style sentence to memorialize the dead branch.",
  "mime": "text/markdown"
}`,
      "",
      "Output JSON only.",
    ].join("\n");
  }

  if (kind === "ISSUE") {
    return [
      seedFrame,
      "Produce a GitHub Issue body — ready to paste into a real repo to start the work.",
      "Strict GitHub-flavored markdown. Include task list with checkboxes.",
      "",
      "Return JSON only:",
      `{
  "kind": "ISSUE",
  "title": "<issue title — short, imperative, ≤72 chars>",
  "labels": ["<3-5 lowercase kebab-case labels>"],
  "body": "<markdown body:\\n## Goal\\n  one paragraph: what we're building and why.\\n## Scope\\n  - [ ] checkbox tasks (5-8 of them). Each one shippable in <2 hours.\\n## Acceptance\\n  - 2-3 concrete done-conditions.\\n## Out of Scope\\n  - 2 bullets of explicit non-goals.\\n## Notes\\n  one paragraph with implementation hints — file paths if obvious, libraries to consider.",
  "mime": "text/markdown"
}`,
      "",
      "Output JSON only.",
    ].join("\n");
  }

  // BADGE
  return [
    seedFrame,
    "Produce a README BADGE — a one-line embeddable artifact for the user's README.",
    "Should be terminal-style, identifying the delusion score and tier visually.",
    "Output an SVG and the markdown snippet to embed it.",
    "",
    "Return JSON only:",
    `{
  "kind": "BADGE",
  "title": "<short label, ALL CAPS>",
  "embed_markdown": "[![Scope Creeper Score](badge-url)](permalink)",
  "body": "<inline SVG string — 240x40, terminal aesthetic, includes score number + tier word + creeper icon. Use monospace font. Black background, tier-colored accent.>",
  "mime": "image/svg+xml"
}`,
    "",
    "Output JSON only.",
  ].join("\n");
}

function repoAgeLabel(pushedAt: string | null): string {
  if (!pushedAt) return "unknown";
  const days = Math.floor((Date.now() - Date.parse(pushedAt)) / 86_400_000);
  if (days < 1) return "today";
  if (days < 7) return `${days}d ago`;
  if (days < 30) return `${Math.floor(days / 7)}w ago`;
  if (days < 365) return `${Math.floor(days / 30)}mo ago`;
  return `${Math.floor(days / 365)}y ago`;
}

export function userProfilePrompt(args: {
  user: { login: string; name: string | null; bio: string | null; publicRepos: number; followers: number; createdAt: string | null };
  repos: { name: string; description: string | null; language: string | null; stars: number; size: number; pushedAt: string | null; archived: boolean }[];
}): string {
  const accountAgeDays = args.user.createdAt
    ? Math.floor((Date.now() - Date.parse(args.user.createdAt)) / 86_400_000)
    : null;
  const ageLabel = accountAgeDays !== null
    ? accountAgeDays > 365
      ? `${Math.floor(accountAgeDays / 365)} years`
      : `${Math.floor(accountAgeDays / 30)} months`
    : "unknown";

  const reposToAnalyze = args.repos.slice(0, 15);
  const repoLines = reposToAnalyze
    .map((r, i) => {
      const archived = r.archived ? " [ARCHIVED]" : "";
      const desc = r.description ? ` — ${r.description.slice(0, 80)}` : "";
      return `  ${i + 1}. ${r.name} (${r.language ?? "?"})${desc} — ${r.size}KB — ${r.stars}★ — last active ${repoAgeLabel(r.pushedAt)}${archived}`;
    })
    .join("\n");

  return [
    `Analyze this GitHub developer's building patterns. Score their scope creep tendency.`,
    ``,
    `Developer: ${args.user.login}${args.user.name ? ` (${args.user.name})` : ""}`,
    `Account age: ${ageLabel}`,
    `Bio: ${args.user.bio ?? "(none)"}`,
    `Total public repos (incl. forks): ${args.user.publicRepos}`,
    `Followers: ${args.user.followers}`,
    ``,
    `Top ${reposToAnalyze.length} repos (most recently active):`,
    repoLines,
    ``,
    `Score 0 = disciplined, focused, consistent shipper.`,
    `Score 100 = serial project abandoner, scope inflation, never ships.`,
    ``,
    `Return JSON only, no markdown:`,
    `{`,
    `  "delusionScore": <int 0-100>,`,
    `  "tier": "corpse"|"sweetspot"|"abyss"|"delusion",`,
    `  "verdict": "<3-6 WORDS ALL CAPS — describe their building pattern>",`,
    `  "analysis": "<one terminal-style sentence about what you observe in their repos>",`,
    `  "patterns": [`,
    `    "<specific observable pattern 1, e.g. '12 of 30 repos abandoned after first week'>",`,
    `    "<specific pattern 2, grounded in the repo list>",`,
    `    "<specific pattern 3>"`,
    `  ]`,
    `}`,
  ].join("\n");
}

export function chatlogIllusionPrompt(chatlog: string): string {
  return [
    "Score the AMBITION (illusion) embedded in this input on a 0-100 scale.",
    "Higher = more sweeping, ungrounded, multi-feature, multi-system claims.",
    "Lower = pragmatic, bounded, ships in a week. A single greeting like 'hello' = ~10.",
    "",
    `Input:\n"""\n${chatlog.slice(0, 8000)}\n"""`,
    "",
    "Return JSON only:",
    `{"illusionScore": <int 0-100>, "claimedFeatures": ["<short feature 1>", "..."], "summary": "<one terminal-style line that captures what this is TRYING to be>"}`,
  ].join("\n");
}
