/**
 * Canonical LLM prompt templates. The Pages Function imports these so
 * that future clients (a CLI, an extension) hit the same prompts.
 *
 * Framing: scope-creeper is a GAME. Every input — even a one-word
 * "hello" — is the seed of a project. The LLM's job is to expand
 * possibility space: surface 4-5 *project ideas* the user could build
 * starting from this seed, and score how delusional each path is to
 * actually ship. Drilling into a dimension = picking that project and
 * generating its own sub-paths.
 */

export const SYSTEM_PROMPT = [
  "You are SCOPE CREEPER, a tactical diagnostic + creative ideation engine.",
  "Your tone is cynical, terminal-glitch, retro-arcade. Speak in short imperatives.",
  "You take ANY input — a repo URL, a chatlog, a single word — and treat it as a SEED.",
  "Your job: surface multiple wild project directions a builder could grow from this seed,",
  "and rate how delusional each is to ship.",
  "Always be specific and generative — never generic. Suggest concrete features, names, weird angles.",
  "Higher delusion = more ambitious / impossible / hilarious. Lower = boring but shippable.",
].join(" ");

export function mutationPrompt(args: {
  realityScore: number;
  illusionScore: number;
  description: string;
}): string {
  return [
    `Reality: ${args.realityScore}/100 (how grounded the seed is).`,
    `Illusion: ${args.illusionScore}/100 (how ambitious it already is).`,
    `Seed:\n"""\n${args.description}\n"""`,
    "",
    "Treat this seed as the kernel of a project. Return JSON with this shape:",
    `{
  "verdict": "<3-6 WORDS, ALL CAPS, terminal-style>",
  "analysis": "<one sentence: what the seed IS, what it could BECOME>",
  "mutations": ["<1-3 absurd-but-specific tweaks to the CURRENT path>"],
  "dimensions": [
    {
      "id": "<short_snake_case_id>",
      "label": "<3-WORDS MAX, ALL CAPS, evocative project name>",
      "blurb": "<one sentence: what THIS project would actually be — name a feature, an interaction, or a wild angle>",
      "creep": <int 0-100 — how delusional is THIS path to ship? 0 = boring weekend script, 100 = decade-long moonshot>
    },
    "<4-5 dimensions total — each a DIFFERENT project path the seed could grow into. SPAN the range: include at least one sane path (low creep), one moonshot (high creep), and a couple in between>"
  ]
}`,
    "",
    "Examples of good dimensions for a 'hello' seed:",
    `  - { "id":"etymology_engine", "label":"ETYMOLOGY ENGINE", "blurb":"Real-time word-origin explorer; trace 'hello' back through Old High German.", "creep": 20 }`,
    `  - { "id":"greeting_agent",   "label":"GREETING AGENT",   "blurb":"AI persona that replies to greetings with a different personality each time.", "creep": 45 }`,
    `  - { "id":"first_word_museum","label":"FIRST-WORD MUSEUM","blurb":"Curated archive of every culture's first-greeting word, voiced by native speakers.", "creep": 78 }`,
    "",
    "Examples for a 'vercel/next.js' seed:",
    `  - { "id":"hook_proliferation","label":"HOOK PROLIFERATION","blurb":"What if every Next page got its own React hook, auto-generated by the build?", "creep": 35 }`,
    `  - { "id":"edge_only","label":"EDGE-ONLY MIGRATION","blurb":"Force every route to edge runtime; see which packages break first.", "creep": 55 }`,
    "",
    "Dimensions are NOT abstract risk categories. Each is a CONCRETE project the user could choose to build.",
    "Output JSON only. No prose, no markdown wrapping.",
  ].join("\n");
}

export function creepScalePrompt(args: {
  parentSummary: string;
  dimensionLabel: string;
  dimensionBlurb: string;
}): string {
  return [
    `Parent project state:\n"""\n${args.parentSummary}\n"""`,
    "",
    `The user just chose to BUILD the "${args.dimensionLabel}" branch (${args.dimensionBlurb}).`,
    "Score this project on the delusion scale (0-100; higher = more delusional).",
    "Then propose 3-4 NEW sub-projects that branch off THIS one if they wanted to push further.",
    "Each sub-project should be a CONCRETE thing they could build, not an abstract risk.",
    "",
    "Return JSON only:",
    `{
  "verdict": "<3-6 WORDS, ALL CAPS>",
  "analysis": "<one sentence: what this branch becomes when scaled, what gets exciting or breaks>",
  "score": <int 0-100 delusion score for THIS branch>,
  "mutations": ["<2-3 absurd-but-specific features to add or invert>"],
  "dimensions": [
    {
      "id": "<id>",
      "label": "<3-WORDS MAX, evocative project name>",
      "blurb": "<one sentence: what THIS sub-project would actually be>"
    },
    "<3-4 sub-dimensions to drill deeper into>"
  ]
}`,
  ].join("\n");
}

export function chatlogIllusionPrompt(chatlog: string): string {
  return [
    "Score the AMBITION (illusion) embedded in this input on a 0-100 scale.",
    "Higher = more sweeping, ungrounded, multi-feature, multi-system claims.",
    "Lower = pragmatic, bounded, ships in a week. A single greeting like 'hello' = ~10.",
    "",
    `Input:\n"""\n${chatlog.slice(0, 8000)}\n"""`,
    "",
    "Return JSON only:",
    `{"illusionScore": <int 0-100>, "claimedFeatures": ["<short feature 1>", "..."], "summary": "<one terminal-style line that captures what this is TRYING to be>"}`,
  ].join("\n");
}
