/**
 * POST /api/github/export-artifact
 *
 * Body: {
 *   artifact: CreepArtifact,
 *   repo: "owner/name",
 *   mode: "issue" | "pr",
 * }
 * Response: { url, kind: "issue" | "pr", branch? }
 *
 * ISSUE mode → opens a real GitHub issue with the artifact body.
 * PR mode    → creates a new branch + commits the artifact file +
 *              opens a PR into the repo's default branch.
 *
 * Requires a valid signed GH OAuth cookie (set by /api/auth/github/callback).
 */
import { NextResponse } from "next/server";
import { getCfEnv } from "@/lib/cf-env";
import { readAuthCookie } from "@/lib/auth-cookie";
import type { ArtifactKind, CreepArtifact } from "@/core";

export const runtime = "edge";

interface Env {
  GITHUB_CLIENT_SECRET?: string;
  AUTH_SECRET?: string;
}
function getEnv(): Env { return getCfEnv<Env>(); }

interface ExportBody {
  artifact?: CreepArtifact;
  repo?: string;
  mode?: "issue" | "pr";
}

function extForArtifact(a: CreepArtifact): string {
  if (a.mime.startsWith("image/svg")) return "svg";
  return "md";
}

function pathForArtifact(a: CreepArtifact, slug: string): string {
  const kind = a.kind.toLowerCase();
  return `SCOPE_CREEPER/${kind}-${slug}.${extForArtifact(a)}`;
}

function slug(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "artifact"
  );
}

function branchName(a: CreepArtifact, s: string): string {
  return `scope-creeper/${a.kind.toLowerCase()}-${s}`;
}

function b64utf8(text: string): string {
  const bytes = new TextEncoder().encode(text);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}

function defaultBodyForArtifact(a: CreepArtifact, fileUrl?: string): string {
  // The PR body shouldn't just dump the file content again — link to it.
  const intro = `This PR adds the **${a.kind}** artifact "${a.title}" generated by [Scope Creeper](https://scopecreeper.pages.dev).\n\n`;
  if (fileUrl) {
    return `${intro}> ${a.title}\n\nFile: [${fileUrl}](${fileUrl})\n\n---\n\n${a.body.slice(0, 4000)}`;
  }
  return `${intro}${a.body.slice(0, 6000)}`;
}

function defaultLabels(kind: ArtifactKind): string[] {
  switch (kind) {
    case "SHIPPABLE": return ["scope-creeper", "shippable-v0"];
    case "KILL":      return ["scope-creeper", "kill"];
    case "ISSUE":     return ["scope-creeper"];
    case "BADGE":     return ["scope-creeper", "documentation"];
  }
}

export async function POST(request: Request): Promise<Response> {
  const env = getEnv();
  const secret = env.AUTH_SECRET ?? `${env.GITHUB_CLIENT_SECRET ?? ""}::sc-auth`;
  const token = await readAuthCookie(request, secret);
  if (!token) {
    return NextResponse.json({ error: "GH_NOT_AUTHENTICATED" }, { status: 401 });
  }

  let body: ExportBody;
  try {
    body = (await request.json()) as ExportBody;
  } catch {
    return NextResponse.json({ error: "invalid JSON" }, { status: 400 });
  }
  if (!body.artifact?.body || !body.artifact?.title) {
    return NextResponse.json({ error: "missing artifact" }, { status: 400 });
  }
  if (!body.repo || !body.repo.includes("/")) {
    return NextResponse.json({ error: "missing repo (owner/name)" }, { status: 400 });
  }
  if (body.mode !== "issue" && body.mode !== "pr") {
    return NextResponse.json({ error: "mode must be 'issue' or 'pr'" }, { status: 400 });
  }
  const [owner, repo] = body.repo.split("/");
  if (!owner || !repo) {
    return NextResponse.json({ error: "repo must be owner/name" }, { status: 400 });
  }

  const ghHeaders = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "User-Agent": "scopecreeper",
    "Content-Type": "application/json",
  };

  // ---- ISSUE mode ----
  if (body.mode === "issue") {
    const labels = body.artifact.labels?.length
      ? Array.from(new Set([...body.artifact.labels, ...defaultLabels(body.artifact.kind)]))
      : defaultLabels(body.artifact.kind);
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues`,
      {
        method: "POST",
        headers: ghHeaders,
        body: JSON.stringify({
          title: body.artifact.title.slice(0, 250),
          body: body.artifact.body,
          labels,
        }),
      }
    );
    if (!res.ok) {
      const detail = await res.text();
      return NextResponse.json(
        { error: `GitHub responded ${res.status}`, detail },
        { status: 502 }
      );
    }
    const data = (await res.json()) as { html_url?: string; number?: number };
    return NextResponse.json({
      url: data.html_url ?? "",
      kind: "issue",
      number: data.number,
    });
  }

  // ---- PR mode ----
  const s = slug(body.artifact.title);
  const branch = branchName(body.artifact, s);
  const filePath = pathForArtifact(body.artifact, s);

  // 1. Lookup default branch.
  const repoMeta = await fetch(
    `https://api.github.com/repos/${owner}/${repo}`,
    { headers: ghHeaders }
  );
  if (!repoMeta.ok) {
    return NextResponse.json(
      { error: `repo lookup failed: ${repoMeta.status}` },
      { status: 502 }
    );
  }
  const repoJson = (await repoMeta.json()) as { default_branch?: string };
  const baseBranch = repoJson.default_branch ?? "main";

  // 2. Get base branch SHA.
  const refRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`,
    { headers: ghHeaders }
  );
  if (!refRes.ok) {
    const detail = await refRes.text();
    return NextResponse.json(
      { error: `base ref lookup failed: ${refRes.status}`, detail },
      { status: 502 }
    );
  }
  const refJson = (await refRes.json()) as { object?: { sha?: string } };
  const baseSha = refJson.object?.sha;
  if (!baseSha) {
    return NextResponse.json({ error: "base SHA missing" }, { status: 502 });
  }

  // 3. Create branch (idempotent: ignore 422 already-exists).
  const newRefRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/refs`,
    {
      method: "POST",
      headers: ghHeaders,
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    }
  );
  if (!newRefRes.ok && newRefRes.status !== 422) {
    const detail = await newRefRes.text();
    return NextResponse.json(
      { error: `branch create failed: ${newRefRes.status}`, detail },
      { status: 502 }
    );
  }

  // 4. Commit the artifact file to the new branch (PUT contents).
  //    If the path already exists on the branch (re-export), include its sha.
  let existingSha: string | undefined;
  const existing = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(filePath)}?ref=${branch}`,
    { headers: ghHeaders }
  );
  if (existing.ok) {
    const e = (await existing.json()) as { sha?: string };
    existingSha = e.sha;
  }
  const commitRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(filePath)}`,
    {
      method: "PUT",
      headers: ghHeaders,
      body: JSON.stringify({
        message: `chore(scope-creeper): add ${body.artifact.kind} :: ${body.artifact.title.slice(0, 60)}`,
        content: b64utf8(body.artifact.body),
        branch,
        sha: existingSha,
      }),
    }
  );
  if (!commitRes.ok) {
    const detail = await commitRes.text();
    return NextResponse.json(
      { error: `commit failed: ${commitRes.status}`, detail },
      { status: 502 }
    );
  }
  const commitJson = (await commitRes.json()) as {
    content?: { html_url?: string };
  };
  const fileUrl = commitJson.content?.html_url;

  // 5. Open the PR. If a PR for this head already exists, surface it.
  const prRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls`,
    {
      method: "POST",
      headers: ghHeaders,
      body: JSON.stringify({
        title: `scope-creeper: ${body.artifact.title.slice(0, 120)}`,
        head: branch,
        base: baseBranch,
        body: defaultBodyForArtifact(body.artifact, fileUrl),
        maintainer_can_modify: true,
      }),
    }
  );
  if (prRes.ok) {
    const prJson = (await prRes.json()) as { html_url?: string; number?: number };
    return NextResponse.json({
      url: prJson.html_url ?? "",
      kind: "pr",
      branch,
      number: prJson.number,
    });
  }
  // PR already exists for this head — look it up and return it.
  if (prRes.status === 422) {
    const existingPr = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/pulls?head=${owner}:${branch}&state=open`,
      { headers: ghHeaders }
    );
    if (existingPr.ok) {
      const arr = (await existingPr.json()) as Array<{ html_url?: string; number?: number }>;
      if (arr[0]?.html_url) {
        return NextResponse.json({
          url: arr[0].html_url,
          kind: "pr",
          branch,
          number: arr[0].number,
          reused: true,
        });
      }
    }
  }
  const detail = await prRes.text();
  return NextResponse.json(
    { error: `PR open failed: ${prRes.status}`, detail },
    { status: 502 }
  );
}
